// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZShAUI_92W8GQfK3-_KhJ6k8kUaBYoU',
    appId: '1:126027206206:web:7b76d8eb2ae19b15fecb6f',
    messagingSenderId: '126027206206',
    projectId: 'bubblenotes-55574',
    authDomain: 'bubblenotes-55574.firebaseapp.com',
    databaseURL:
        'https://bubblenotes-55574-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblenotes-55574.appspot.com',
    measurementId: 'G-ZW75LBG529',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPnx_ZhEfT5qkUdskwKPZaA6bxuTSDphQ',
    appId: '1:126027206206:android:b51e50f0bc439077fecb6f',
    messagingSenderId: '126027206206',
    projectId: 'bubblenotes-55574',
    databaseURL:
        'https://bubblenotes-55574-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblenotes-55574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZkzb_m6KapDou26MU5k7Xb8IuDWjDts',
    appId: '1:126027206206:ios:9d1c8908cd12a6edfecb6f',
    messagingSenderId: '126027206206',
    projectId: 'bubblenotes-55574',
    databaseURL:
        'https://bubblenotes-55574-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblenotes-55574.appspot.com',
    iosBundleId: 'com.omen.bubblenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZkzb_m6KapDou26MU5k7Xb8IuDWjDts',
    appId: '1:126027206206:ios:5ca5130f8ad37557fecb6f',
    messagingSenderId: '126027206206',
    projectId: 'bubblenotes-55574',
    databaseURL:
        'https://bubblenotes-55574-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bubblenotes-55574.appspot.com',
    iosBundleId: 'com.omen.bubblenotes.RunnerTests',
  );
}
