name: Flutter APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "17.0.10"
          distribution: "temurin"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.4"

      - name: Setup JKS
        env:
          JKS_FILE: ${{ secrets.JKS_FILE }}
        run: echo $JKS_FILE > ./key.jks

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi --release --key-store-path=./key.jks --key-store-password=${{ secrets.KEY_STORE_PASSWORD }} --key-alias=${{ secrets.KEY_ALIAS }} --key-password=${{ secrets.KEY_PASSWORD }}

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
